spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        #          filters:
        #            - AuthenticationFilter

#        - id: payment-app
#          uri: lb://PAYMENT-SERVICE
#          predicates:
#            - Path=/api/v1/payment/**
#          filters:
#            - AuthenticationFilter
#
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/order/**
#          filters:
#            - AuthenticationFilter





server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

